name: Django Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    # service containers to run with `postgres-job`
    services:
      # label used to access the service container
      postgres:
        # Docker Hub image
        image: postgres:latest
        # service environment variables
        # `POSTGRES_HOST` is `postgres`
        env:
          # optional (defaults to `postgres`)
          POSTGRES_DB: postgres_db
          # required
          POSTGRES_PASSWORD: postgres_password
          # optional (defaults to `5432`)
          POSTGRES_PORT: 5432
          # optional (defaults to `postgres`)
          POSTGRES_USER: postgres_user
        ports:
          # maps tcp port 5432 on service container to the host
          - 5432:5432
        # set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - name: Checkout code
      uses: actions/checkout@v2



    - name: Install dependencies
      run: |
        sudo apt-get install python3-dev libpq-dev
        pip install -r requirements.txt

    - name: Create PostgreSQL user and database
      run: |
        psql -h localhost -U postgres_user -c "CREATE DATABASE postgres_db OWNER postgres_user;"

    - name: Apply migrations
      run: python manage.py migrate

    - name: Run Django tests
      run: python manage.py test

    # Add a step to generate test coverage report (example using coverage.py)
    # ...
